export const SET_AUDIT_STATISTICS_INFO = "SET_AUDIT_STATISTICS_INFO";
export const SET_ONLINE_TIME = "SET_ONLINE_TIME";
export const CLEAR_TIMER = "CLEAR_TIMER";
export const SIGN_OUT = "SIGN_OUT";
export const SET_USERINFO = "SET_USERINFO";
export const SET_COUNT_TOTAL = "SET_COUNT_TOTAL";
export const SET_COUNT_TOTAL_CHANGE = "SET_COUNT_TOTAL_CHANGE";
export const SET_OPINION_COUNT = "SET_OPINION_COUNT";
export const SET_AUDIT_STATISTICS_INFO_YM = "SET_AUDIT_STATISTICS_INFO_YM";
export const SET_AUDITED_SEARCHLIST_YM = "SET_AUDITED_SEARCHLIST_YM";

